spring:
  redis:
    database: 0
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/finalproject?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: zhengyang0921
    driver-class-name: com.mysql.cj.jdbc.Driver
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
mybatis:
#mapper映射文件路径
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.zy.final_project.entity
server:
  port: 8181